version: '3.8'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - /home/paulolirio/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
